<?php
$pageTitle = 'WorldTrends - Charts';
$currentPage = 'charts';
$pageScript = '/assets/js/charts-d3.js';
include 'includes/header.php';
?>

<section class="charts-header">
    <h1>Charts</h1>
    <div class="chart-stats">
        <div class="stat-item">
            <span class="stat-label">Network Usage</span>
            <span class="stat-value" id="chart1-value">Loading...</span>
        </div>
        <div class="stat-item">
            <span class="stat-label">Storage Usage</span>
            <span class="stat-value" id="chart2-value">Loading...</span>
        </div>
    </div>
</section>

<section class="chart-navigation">
    <div class="month-carousel">
        <button class="carousel-btn carousel-prev" id="carousel-prev">‹</button>
        <div class="month-timeline-container">
            <div class="month-timeline">
                <!-- Timeline will be generated by D3 app -->
            </div>
        </div>
        <button class="carousel-btn carousel-next" id="carousel-next">›</button>
    </div>
</section>

<section class="chart-container" id="chart-container">
    <!-- D3.js chart will be rendered here -->
</section>

<section class="chart-legend">
    <div class="legend-items">
        <div class="legend-item">
            <div class="legend-color" style="background-color: #ef4444;"></div>
            <span>Network Usage</span>
        </div>
        <div class="legend-item">
            <div class="legend-color" style="background-color: #3b82f6;"></div>
            <span>Storage Usage</span>
        </div>
    </div>
    <div class="chart-help">
        <p>💡 Click on any month to view daily breakdown</p>
    </div>
</section>

<?php include 'includes/footer.php'; ?> 