<?php
  require_once __DIR__ . '/../includes/constants.php';

  $pageTitle = PAGE_TITLE_CHARTS;
  $currentPage = PAGE_CHARTS;
  $pageScript = JS_CHARTS;

  include INCLUDES_PARTS . '/header.php';
?>

<div class="container">
  <section class="charts-section">
    <div class="charts-section__header">
      <h1 class="charts-section__title">Charts</h1>
      <div class="charts-section__stats">
        <div class="stats__item">
          <span class="stats__label">Network Usage</span>
          <span class="stats__value stats__value--primary" id="<?= ID_CHART1_VALUE ?>"><?= MSG_LOADING ?></span>
        </div>
        <div class="stats__item">
          <span class="stats__label">Storage Usage</span>
          <span class="stats__value stats__value--secondary" id="<?= ID_CHART2_VALUE ?>"><?= MSG_LOADING ?></span>
        </div>
      </div>
    </div>
  </section>

  <section class="charts-section__navigation">
    <div class="month-carousel">
      <button class="month-carousel__btn btn--ripple-hover" id="<?= ID_CAROUSEL_PREV ?>">
        <?= renderIcon('arrow-left', 20, 20) ?>
      </button>

      <div class="month-timeline__container">
        <div class="month-timeline">
          <!-- Timeline will be generated by Chart.js app -->
        </div>
      </div>

      <button class="month-carousel__btn btn--ripple-hover" id="<?= ID_CAROUSEL_NEXT ?>">
        <?= renderIcon('arrow-right', 20, 20) ?>
      </button>
    </div>
  </section>

  <section class="chart-container" id="<?= CHART_CONTAINER_ID ?>">
    <!-- Chart.js chart will be rendered here -->
  </section>

  <section class="chart-legend">
    <div class="chart-legend__items">
      <div class="chart-legend__item">
        <div class="chart-legend__color" style="background-color: var(--color-chart-1);"></div>
        <span>Network Usage</span>
      </div>
      <div class="chart-legend__item">
        <div class="chart-legend__color" style="background-color: var(--color-chart-2);"></div>
        <span>Storage Usage</span>
      </div>
    </div>
    <div class="chart-legend__help">
      <p class="chart-legend__help-text">💡 Click on any month to view daily breakdown</p>
    </div>
  </section>
</div>

<?php include INCLUDES_PARTS . '/footer.php'; ?>